# Generated by Django 4.2.20 on 2025-05-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_unit_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
