# Generated by Django 4.2.20 on 2025-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorites_user_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(blank=True, max_length=1, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
