# Generated by Django 4.2.20 on 2025-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Граммы'), ('мл', 'Миллилитры'), ('шт.', 'Количество в штуках'), ('ч. л.', 'Чайная ложка'), ('ст. л.', 'Столовая ложка'), ('щепотка', 'Щепотка'), ('капля', 'Капля'), ('стакан', 'Стакан'), ('банка', 'Банка'), ('по вкусу', 'По вкусу')], max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
