# Generated by Django 4.2.20 on 2025-05-21 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть меньше \n1'), django.core.validators.MaxValueValidator(1000000, message='Значение должно быть больше \n1000000')], verbose_name='Количество'),
        ),
    ]
