# Generated by Django 4.2.20 on 2025-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_favorites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_favorites_unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_shoppinglist_unique_user_recipe'),
        ),
    ]
