# Generated by Django 4.2.20 on 2025-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_subscription_unique_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='users/images/', verbose_name='Аватар пользователя'),
        ),
    ]
